spring:
  application:
     name: spot-share

  datasource:
    url: ${db-url}
    username: ${db-uname}
    password: ${db-pass}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    show-sql: true

  cache:
    type: redis
  data:
    redis:
      host: ${redis-host}
      password: ${redis-pass}
      port: ${redis-port}
      timeout: 60000
